"""
Django settings for synchro project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-4tn4^f2s)^%(2ucbjf8@i1q^g@v9-#ipu=738pf*nui&4o9s8t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'synchro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'synchro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración del modelo de usuario personalizado
# Esto indica a Django que use nuestra clase Usuario en lugar de la básica
AUTH_USER_MODEL = 'usuarios.Usuario'

# ---------------------------------------------------------------------------
# Configuración de Django Rest Framework
#
# ¿QUÉ ES ESTO?
# Aquí se le dice a DRF cómo debe autenticar las peticiones a la API.
# Con esta configuración, TODOS los endpoints protegidos (con IsAuthenticated)
# requieren un token JWT en el header de la petición HTTP.
#
# ¿CÓMO SE USA DESDE EL FRONTEND?
# En cada petición HTTP que requiera autenticación, se debe enviar el header:
#   Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOi...
#
# Si NO se envía el header → la API responde con 401 Unauthorized
# Si se envía un token expirado → la API responde con 401 Unauthorized
# ---------------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # JWTAuthentication: Verifica que el token del header sea válido
        # y no haya expirado. Si es válido, asigna el usuario a request.user.
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

from datetime import timedelta

# ---------------------------------------------------------------------------
# Configuración de Simple JWT (JSON Web Token)
#
# JWT es un estándar de autenticación sin estado (stateless). El servidor
# genera un token firmado que el frontend guarda (en localStorage, cookies, etc.)
# y envía en cada petición. El servidor verifica la firma sin consultar la DB.
#
# FLUJO DE AUTENTICACIÓN JWT:
#
# ┌─────────────────────────────────────────────────────────────────────┐
# │  1. LOGIN: POST /api/usuarios/login/                               │
# │     → Enviar: { "email": "...", "password": "..." }                │
# │     → Recibir: { "access": "eyJ...", "refresh": "eyJ..." }        │
# │                                                                     │
# │  2. USAR LA API: Incluir el access token en cada petición          │
# │     → Header: Authorization: Bearer eyJ...                         │
# │                                                                     │
# │  3. TOKEN EXPIRADO (después de 1 día):                             │
# │     → POST /api/usuarios/login/refresh/                            │
# │     → Enviar: { "refresh": "eyJ..." }                              │
# │     → Recibir: { "access": "nuevo_eyJ...", "refresh": "nuevo..." } │
# │                                                                     │
# │  4. REFRESH EXPIRADO (después de 7 días):                          │
# │     → El usuario debe hacer login de nuevo                         │
# └─────────────────────────────────────────────────────────────────────┘
# ---------------------------------------------------------------------------
SIMPLE_JWT = {
    # Cuánto tiempo dura el token de ACCESO antes de expirar.
    # Este es el token que se envía en el header Authorization.
    # Después de 1 día, el frontend debe usar el refresh token para obtener uno nuevo.
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),

    # Cuánto tiempo dura el token de REFRESCO antes de expirar.
    # Este token solo se usa para obtener un nuevo access token.
    # Después de 7 días sin actividad, el usuario debe hacer login de nuevo.
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    # ROTATE_REFRESH_TOKENS = True:
    # Cada vez que se usa el refresh token, se genera uno NUEVO.
    # Esto mantiene la sesión "viva" mientras el usuario siga usando la app.
    # Ejemplo: Si el usuario usa la app todos los días, nunca tendrá que
    # volver a hacer login porque siempre recibe un refresh token nuevo.
    'ROTATE_REFRESH_TOKENS': True,

    # BLACKLIST_AFTER_ROTATION = False:
    # Si fuera True, el refresh token anterior se invalidaría al rotarse.
    # Con False, los tokens antiguos siguen siendo válidos hasta que expiren.
    # Nota: Para activar blacklist se necesita agregar 'rest_framework_simplejwt.token_blacklist'
    # a INSTALLED_APPS y correr las migraciones correspondientes.
    'BLACKLIST_AFTER_ROTATION': False,

    # ALGORITHM: Algoritmo de encriptación para firmar el token.
    # HS256 = HMAC con SHA-256 (simétrico, usa la misma clave para firmar y verificar)
    'ALGORITHM': 'HS256',

    # SIGNING_KEY: La clave secreta usada para firmar los tokens.
    # Usamos la misma SECRET_KEY de Django. Si alguien obtiene esta clave,
    # podría generar tokens válidos para cualquier usuario → MANTENERLA SEGURA.
    'SIGNING_KEY': SECRET_KEY,

    # AUTH_HEADER_TYPES: El prefijo que se usa en el header Authorization.
    # Con ('Bearer',), el header debe ser: Authorization: Bearer eyJ...
    # Otros sistemas usan 'Token' o 'JWT' como prefijo.
    'AUTH_HEADER_TYPES': ('Bearer',),

    # USER_ID_FIELD: El nombre del campo en el modelo Usuario que se usa como ID.
    # En nuestro caso es 'id_usuario' (no 'id' porque usamos un primary key personalizado).
    'USER_ID_FIELD': 'id_usuario',

    # USER_ID_CLAIM: El nombre de la clave DENTRO del payload del token JWT.
    # Al decodificar el token, encontrarás: { "user_id": "1", ... }
    # SimpleJWT usa este valor para identificar al usuario en cada petición.
    'USER_ID_CLAIM': 'user_id',
}

import os
# Configuración para archivos subidos por el usuario (fotos de perfil, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

